schema_version: 1

context:
  name: azure-mgmt-loganalytics
  version: 13.0.0b7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/3c/fb/7119a3f0861b7d3a2680c1baf11e5f245f7a0166c23f519e3aea77bd2dec/azure_mgmt_loganalytics-13.0.0b7.tar.gz
  sha256: 934001a4a61e3e821a6344f2a8b265d53462f09bf92dfe65699cf4f89515a3e5

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.dev0
    - azure-mgmt-core >=1.3.2
    - isodate >=0.6.1
    - typing-extensions >=4.6.0


tests:
  - python:
      imports:
        - azure.mgmt.loganalytics
        - azure.mgmt.loganalytics.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Log Analytics Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
