schema_version: 1

context:
  name: azure-mgmt-loganalytics
  version: 13.0.0b4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-loganalytics-${{ version }}.zip 
  sha256: 266d6deefe6fc858cd34cfdebd568423db1724a370264e97017b894914a72879

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.3.0,<2.0
    - msrest >=0.6.21

tests:
  - python:
      imports:
        - azure.mgmt.loganalytics
        - azure.mgmt.loganalytics.aio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Log Analytics Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
